### ISSUE TITLE
config file error

### ISSUE THREAD

**Issue by devinity1337** [Singh-Lab/DeMaSk#2]
`predict.py: error: Unable to open config file: /anaconda/envs/azureml_py38/lib/python3.8/site-packages/demask/../config.ini. Error: No such file or directory`

I get this error even when I have config.ini in my demask directory in anaconda.

**Comment by daniel-munro** [comment]
Oh thanks, I didn't realize that installing the PyPI demask package only provides the inner demask/ directory containing the Python code, but by default demask looks for the config file in the outer DeMaSk/ directory. That outer directory also contains data/ which contains the precomputed model parameters used for prediction. I could move the config and parameter files inside the demask/ directory so they're included with the pip install, but I don't think it's a good idea to require files inside site-packages/ to be edited.

Would you be able to uninstall demask and instead clone this repo and use pip to install demask from that directory (see the README)? If so, I'll just remove the package from PyPI, as now I don't think it will work well for this kind of package.

**Comment by devinity1337** [comment]
Hi,

I pip installed from the cloned repo but now demask.predict doesn't work:
`python3 demask.predict -i X_alignment.fasta -o X_demask.txt`

`python3: can't open file 'demask.predict': [Errno 2] No such file or directory
`

**Comment by daniel-munro** [comment]
You have to include the `-m` tag, e.g. `python3 -m demask.predict ...` to run the module as a command line script.
